### ISSUE TITLE
System.Collections.Concurrent missing from Mono.mscorlib bindings

### ISSUE THREAD

**Issue by lemonmojo** [ThesaurusSoftware/Dubrovnik#24]
Just noticed that bindings for `System.Collections.Concurrent` are missing. Would it be possible to generate bindings for that collection of classes?

**Comment by Thesaurus** [comment]
If you edit mscorlib.codegen.config.objc.xml you can copy the following from <TypeNameSkipList>

		<string>System.Collections.Concurrent.ConcurrentDictionary`2</string>
		<string>System.Collections.Concurrent.ConcurrentQueue`1</string>
		<string>System.Collections.Concurrent.ConcurrentStack`1</string>
		<string>System.Collections.Concurrent.EnumerablePartitionerOptions</string>
		<string>System.Collections.Concurrent.IProducerConsumerCollection`1</string>
		<string>System.Collections.Concurrent.OrderablePartitioner`1</string>
		<string>System.Collections.Concurrent.Partitioner</string>
		<string>System.Collections.Concurrent.Partitioner`1</string>

and copy it into the <TypeNameWhiteList> section.

Regernarte the bindings and your classes will hopefully appear.

The idea is that you can customise the config.objc.xml to control just which classes get bound.
I have windows batch files (generate.bat) that automate regenerating one or all of all the BCL assembles.
If you are regenerating on macOS you might need to do it manually or pull together some shell scripts.

**Comment by lemonmojo** [comment]
Thx for the help, PR https://github.com/ThesaurusSoftware/Dubrovnik/pull/25 waiting for you.

**Comment by Thesaurus** [comment]
You might see that some member functions in the generated classes have been skipped.
This occurs if the member function return type or method signature includes non bound types.
If you need a binding for a skipped method you need to ensure that bindings exist for all its signature types.

**Comment by lemonmojo** [comment]
You're right, there are around 20 skipped methods and constructors. Should I make sure those resolve properly or do you want to merge the PR as is and work on them later?

**Comment by Numpsy** [comment]
Speaking of missing bits, is there an official position on getting new things added to the base repo?

We've hit a few issues with missing interfaces in the base collections (e.g. IList<T> seems to be missing, and the ReadOnlyCollection interfaces would be nice as well) - can add extra full classes to our own libs, but missing lower level bits require regenration of mscorlib etc.).

(We're currently building with the new customised version at https://github.com/Numpsy/Dubrovnik/commit/5ae5b1c52a5641a827607eead069e466ed646e54).

**Comment by Numpsy** [comment]
(by which i of course mean IListA1, without the markup having cut the angular brackets off)

**Comment by KosmicTask** [comment]
We use Dubrovnik to power the macOS port of our Windows product. So basically the set of bound classes reflect the types used in our application assemblies. If we generate bindings for our application assemblies and find that a method has been skipped due to a missing BCL or other .NET framework type then we tweak the xml to get bindings for the missing types (so I just leave skipped methods well alone until a build failure forces me to implement them). Obviously your and any other usage scenario will be different - you may need to bind a wider or narrow range of classes.

However, it makes sense that the master branch contains a sane set of commonly used bindings - it seems weird to me that I didn't encounter a need for IListA1 - I may have worked my away around this some way in the past. So I am open to PRs that bind additional core classes. I may well find myself needing them too!

Obviously binding more types makes for bigger libs, slower builds and tedious Xcode indexing. I would be reluctant to bind all of, for example, System.Security and the Runtime.Interop stuff. But we can easily pull more commonly used individual classes out of these extensive namespaces.

**Comment by lemonmojo** [comment]
+1 on the Xcode indexing issue. It actually never finishes for me once I have all the system bindings in the workspace. And that is on an 8k € iMac Pro... I will probably try to switch to pre compiled libs in the next couple days and check if that improves things. Good thing I have enough cores to not notice any slowdowns ;)

**Comment by Numpsy** [comment]
We're the same here, creating bindings for Windows originated libs on the Mac project (with an ever growing list of bindings as well).
We've were using a patched version of an old Dubrovnik (with a lot more manually generated bindings), and are in the process of updating, hence the requests for extra bits.

We actually have a few bindings for things in corlib (e.g. FileStream) built on top of the base frameworks rather than buuilt into them and that works ok, though not much help for base things like missing interfaces.

In any case, i've made a pull request for IListA1 and a few of the IReadOnly interfaces (causes the Concurrent bindings to be regenerated with extra bits).
Might send a pull to add ReadOnlyCollection if that would be ok, as although it works in a seperate build you lose a ferw things like AsReadOnly on Last that can be useful.

**Comment by KosmicTask** [comment]
No problem. I will try and merge these in later today and just confirm that the unit tests are still happy.

My list of required bindings is ever expanding too (I added some remoting stuff recently) - hence the work that was done to support the codegen config xml. Trying to keep on top of the required bindings manually was just way too painful.
