### ISSUE TITLE
The functionality of System.Collections.ObjectModel.ObservableCollection

### ISSUE THREAD

**Issue by Numpsy** [ThesaurusSoftware/Dubrovnik#8]
Right, next task:

I have some managed libs that make a lot of use of System.Collections.ObjectModel.ObservableCollection, and Dubrovniks implementation is currently just an empty stub. I'm therefore looking at adding some functions to get things from the collection (wip: https://github.com/Numpsy/Dubrovnik/commit/36cd8b1de3f1d6fbaf57fffac01037fd7c101e8f)

A couple of questions:

1) I have the Items member returning a DBSystem_Collections_Generic_ListA1 rather than the .NET IList. Is that ok in the corelib files, or should I return the .net type and convert it later?

2) System.Collections.ObjectModel.Collection is only implementing the interfaces which already have adoption protocols declared rather than the full set. Related to that, it should use  System.Collections.Generic.IList(A1) but there is currently only a System_Collections_Generic_ListA1 class (No I) - just wondering what name the protocol should use in that case?

Thanks.

**Comment by KosmicTask** [comment]
In my own model classes I always return DBSystem_Collections_Generic_ListA1 however I am not sure if that will work in mscorlib, try and see. 

I don't much like my use of the DB managed subclasses. They really exist to add convenience functionality rather than override exiting functionality so redefining them as categories sounds appealing - I know I define the odd property but associated objects could take care of those few cases in a category.

Again, managed Interface handling is something that I feel I haven't got quite right, the details of exposing explicit managed interfaces to Obj-C always seems to get the better of me. However, if you need System_Collections_Generic_IListA1 then just define a stub for it.

**Comment by Numpsy** [comment]
As it stands, I have it building and working for my current requirement with the commit linked above (I only currently need to read the items from the ObservableCollection, no need for its advanced abilities).

Saying that, it looks like i'll need to do the same for some ReadOnly collection types later, so i'll need to revisit it any way.

**Comment by Numpsy** [comment]
(closed this as it seems somewhat out of date)
